### ISSUE TITLE
A1 Mapa mental

### ISSUE THREAD

**Issue by Diegocruz040708** [SistemasTecTlaxiaco/actividad-1-mapa-mental-Diegocruz040708#1]
![Diego Cruz Cruz](https://user-images.githubusercontent.com/112030705/187794339-5a4e2d8d-87c2-49a0-b2a9-4abdbe579ada.png)

**Comment by Daniel-Velasco-Lopez** [comment]
De acuerdo a la rúbrica, has obtenido un 18.8% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
